### ISSUE TITLE
Exclusion Prefix - styles that have a leading . still being exported

### ISSUE THREAD

**Issue by tsarjeant** [lukasoppermann/design-tokens#127]
I am attempting to export the color styles my design team has set up and they are "hiding" certain colors that they don't want to be used for now. It appears the default behavior should exclude these colors as the hidden styles have a leading . 

However, my export is still including them. Is there something I may be missing or need to set up for this to work?

**Comment by lukasoppermann** [comment]
Hey @tsarjeant this should actually work. Both in my automated tests and in the integration test a token prefix with "." gets excluded. 

Can you send me a screenshot of the token names and of your settings? There may me something in there.

**Comment by tsarjeant** [comment]
Is this what youre looking for? 
When I run the export the colors like `Homer>.700` still show up in the export file. 
![Screen Shot 2021-07-15 at 11 32 24 AM](https://user-images.githubusercontent.com/757937/125824376-e198afb4-49f2-4612-a2cd-42987d96f2cf.png)
![Screen Shot 2021-07-15 at 11 31 59 AM](https://user-images.githubusercontent.com/757937/125824386-b3ee017f-1fb8-49c9-8ea1-1136b5b9f874.png)

`"additional": {
      "homer": {
        "50": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(255, 251, 239, 1)",
          "type": "color"
        },
        "200": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(255, 243, 200, 1)",
          "type": "color"
        },
        "300": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(255, 224, 124, 1)",
          "type": "color"
        },
        "800": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(241, 166, 54, 1)",
          "type": "color"
        },
        ".700": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(246, 181, 53, 1)",
          "type": "color"
        },
        ".600": {
          "category": "color",
          "exportKey": "color",
          "value": "rgba(250, 188, 30, 1)",
          "type": "color"
        },`

**Comment by lukasoppermann** [comment]
Ahh, okay then it makes sense. Has this been working before?

The plugin only supports first-level excludes. It basically only checks if the name starts with a dot and the name of this token starts with `additional/homer/.700`.

So maybe you can create a feature request for this.

**Comment by tsarjeant** [comment]
Ah alright, well at least i know I'm not crazy lol. 
I am actually just setting this up for the first time so no it hasn't worked before. 

Ill put in a feature request for this functionality then and see if we can get there. 
Thanks!
