### ISSUE TITLE
[Question/Issue] No size units in output file from styledictionary

### ISSUE THREAD

**Issue by janina3** [lukasoppermann/design-tokens#128]
The font-size var is not working. The CSS (and JSON) output file does not have have a unit (px), though pixel was defined in the exported JSON file. Without the unit in the CSS, the font-size attribute is not working. I'm using HTML/CSS on VSCode. Once I added "px" on line 114, the font-size var worked.
<img width="303" alt="Screen Shot 2021-07-22 at 11 16 40 AM" src="https://user-images.githubusercontent.com/10778810/126673511-90b18b49-96a7-44ff-85a8-dc37442da51d.png">
<img width="446" alt="Screen Shot 2021-07-22 at 11 17 27 AM" src="https://user-images.githubusercontent.com/10778810/126673517-0b118883-68c3-42f0-9445-682997aceac6.png">

**Comment by lukasoppermann** [comment]
Hey, to transform sizes correctly you need to use custom transforms.

I added an example to the transformer repo: https://github.com/lukasoppermann/design-token-transformer/blob/main/transformTokens.js#L5-L53
