### ISSUE TITLE
No design token detected! when trying to export tokens for component

### ISSUE THREAD

**Issue by iamdriz** [lukasoppermann/design-tokens#131]
I've created a simple Button component and when I try to export the tokens for it I get the error No design token detected!

![image](https://user-images.githubusercontent.com/801252/129396995-9073d8dc-1033-417b-b6c7-6435ebfec1b8.png)

I feel like I'm missing something? But I thought it automatically exported styles as tokens and you didn't need to give anything specific names unless you're creating custom tokens...

**Comment by lukasoppermann** [comment]
Hey, you may have encountered a bug.

Can you do me a favor and add a frame named _tokens as a top level frame and see if it works with that?

**Comment by iamdriz** [comment]
Nope doesn't work... here's a link to the Figma if that helps: https://www.figma.com/file/6TA1fHpOwylekqHk6vc2Zg/Untitled?node-id=0%3A1 I've enabled editing.

**Comment by lukasoppermann** [comment]
Hey @iamdriz I am sadly not having edit rights yet.

However do you have styles set up? It looks like you are using a normal color and not a color style, but maybe this due to the view only access.

**Comment by iamdriz** [comment]
@lukasoppermann Sorry mate, I'm new to Figma. You should have edit permissions now.

**Comment by lukasoppermann** [comment]
Hey, no worries. I added another frame where I use styles. This made it work.

You need to work with styles, normal colors / type, etc. are not exported. 

Reopen the ticket if you still have issues.

**Comment by iamdriz** [comment]
@lukasoppermann Ah okies.... so it just exports high-level styles... I thought it would export tokens at the component-level e.g. the button background color and button border radius etc...

**Comment by lukasoppermann** [comment]
Correct, it only exports styles. You could create styles for every component e.g. "button/background-color", etc. but they need to be styles.
