### ISSUE TITLE
cross referencing

### ISSUE THREAD

**Issue by Diemietrie** [lukasoppermann/design-tokens#133]
Is there a way to create a color variable with another color token? How does this work?

**Comment by lukasoppermann** [comment]
Related to #125 

Currently this is not possible. If you have a proposal for a good implementation I would love to hear it.

What makes it complicated is that you would need to update tokens that are related when one of the changes.

**Comment by Diemietrie** [comment]
Ah too bad. 

I know that makes it complicated. I think users of your plugin would need a UI window to set these references. I've been using another plugin to do this, but this plugin doesn't create code for 'style dictionary'. I was able to create these color variables with cross references as their value with this UI.

![image](https://user-images.githubusercontent.com/4568861/130225289-7b394ea3-e9f7-43bf-8c59-4d79c8da7153.png)
![image](https://user-images.githubusercontent.com/4568861/130225583-4842d300-0757-45a0-8487-6ffdbcc6b34c.png)

The name of the plugin is Figma tokens.

**Comment by lukasoppermann** [comment]
Closing in favour of #125
