### ISSUE TITLE
Unable to remove token library added to my account by the plugin.

### ISSUE THREAD

**Issue by Ben-Ruzo** [lukasoppermann/design-tokens#139]
Hi, 

I installed the Design Tokens plugin to try it out and it added this library to my account, which I don't think I created and have been unable to remove.

![Design Tokens for Figma - library](https://user-images.githubusercontent.com/8533709/131852485-23a8e06e-6104-4348-af18-43a7809e55e2.png)

The library seems to only include two color styles.
![Design Tokens for Figma - library styles](https://user-images.githubusercontent.com/8533709/131852981-dd4f52cc-c549-4596-acb0-651181f00789.png)

And when I click on the "Open file" button for this library, it takes me to this "Design Tokens for Figma" file, which is not in my account.
![Design Tokens for Figma - file](https://user-images.githubusercontent.com/8533709/131853129-34597285-f4bf-454b-bbf0-31ccc50422d4.png)

How do I remove this library from my account?

**Comment by lukasoppermann** [comment]
Hey @Ben-Ruzo this is just the demo file.
I think by simply deleting the file from your drafts / recents it should go away. Can you please give it a try?

I also unpublished it, as there is no need for it to be a library.

If this does not help you may have to go into the file, click on "Share" and set yourself to "Leave"

**Comment by Ben-Ruzo** [comment]
I had deleted the demo file a while ago but the library was still showing up for it. It looks like you unpublishing the file, removed it from my library.

I did try to remove myself from the "Share" list but that list is so long and not in alphabetical order, I could not find name. There should be a search feature for that list.

I don't understand why your published library was showing up in my account.

Thank you for your help.

**Comment by lukasoppermann** [comment]
I noticed the same with a file somebody shared with me a year ago and had to try it out. Removing me from the share list was the only action that helped (without them unpublishing it).

This is definitely one of Figmas more quirky behaviors, but I am happy it worked now.
