### ISSUE TITLE
font design tokens transform to [object Object]

### ISSUE THREAD

**Issue by caoimghgin** [lukasoppermann/design-tokens#144]
Love the ability to export JSON for typography. However, the output now only renders [object Object] through style-dictionary. Difficult to say if the latest style-dictionary introduced an incompatibility or not. Worth noting, Supernova.io JSON output for typography has the same behavior.

![Screen_Shot_2021-09-25_at_8 45 30_AM](https://user-images.githubusercontent.com/701989/134809497-aea8649a-da8c-4d08-be87-a8842206e8d3.png)

EXAMPLE JSON OUTPUT:

{
  "font": {
    "hero": {
      "x-large": {
        "type": "custom-fontStyle",
        "value": {
          "fontSize": 96,
          "textDecoration": "none",
          "fontFamily": "CVS Health Sans",
          "fontWeight": 700,
          "fontStyle": "normal",
          "fontStretch": "normal",
          "letterSpacing": -2.16,
          "lineHeight": 100,
          "paragraphIndent": 0,
          "paragraphSpacing": 26,
          "textCase": "none"
        }
      },...

**Comment by lukasoppermann** [comment]
Hey @caoimghgin sorry for the inconvenience, this is the same situation as here: https://github.com/lukasoppermann/design-token-transformer/issues/8

The quick and easy solution is to just change the token export format back to `original`. See more here: [Token format](https://github.com/lukasoppermann/design-tokens#token-format)

I will hopefully get around adding an FAQ part to the repo this upcoming week.

Let me know if you have any more questions.
