### ISSUE TITLE
Font-Weight labels are not parsed correctly

### ISSUE THREAD

**Issue by Mauns** [lukasoppermann/design-tokens#147]
Hey Lukas,

Superb plugins, it helps us a lot. Working with a Typeface from KlimType (Söhne) I noticed that the font-weights are not getting parsed correctly. I compared it with Roboto and it seems like it is because of the labels of the font-weights.

Söhne uses Labels like Leicht, Buch, Halbfett, Fett. This probably not what the plugin expects. Due to this all styles are getting exported with a font-weight: 400.

Cheers —
Marvin

**Comment by lukasoppermann** [comment]
Hey Manus,

this is a very easy fix. You just need to add them to the matrix here: https://github.com/lukasoppermann/design-tokens/blob/main/src/extractor/extractFonts.ts#L23-L39

Would be awesome if you could send a PR for this.

**Comment by lukasoppermann** [comment]
This should work now, thanks to the PR
