### ISSUE TITLE
Custom typography tokens

### ISSUE THREAD

**Issue by markacianfrani** [lukasoppermann/design-tokens#148]
How would one go about creating custom tokens for individual typography categories? For example,

```
--font-weight-light
--font-weight-regular
--font-weight-medium
--font-weight-bold
--font-family-mono
--font-family-sans
--font-size-sm
--font-size-base
--font-size-lg
--font-size-xl
--font-size-2xl
```

Figma's typography styles have multiple properties, but I'd like to divorce our tokens from those. `--font-size-lg` vs ` --font-h1-font-size`

Would there be any interest in a PR for adding font weight, family, size, line-height, etc to the custom tokens setup?

**Comment by lukasoppermann** [comment]
I think what would be better is to use amazon style dictionary to take the styles apart into the individual properties. (Using standard token format).

If you use the original format this should work like this already.

If you want to add an example to the examples folder for the standard tokens and how to extract the size family and weight, I would love a PR for this.

**Comment by markacianfrani** [comment]
That's what I was struggling with in Style Dictionary. There's no real metadata or anything to be able to do something like "--font-size-2xl." 

I could do some transforms or formatting but then all that logic would live inside Style Dictionary where designers can't change anything. 

I'm thinking we'll just create a separate page like we would for spacing and work on a PR to add font weight, font size, etc as additional custom tokens.

**Comment by lukasoppermann** [comment]
Wait, if I understand you correctly (now) you want to basically allow users to define tokens for font-size, font-weight, etc. like `border-radius` so instead of using the `radius` prefix you would use the `fontSize` prefix, is that correct?

That does sound interesting.

**Comment by markacianfrani** [comment]
Exactly. fontSize, fontWeight, fontFamily and letterSpacing all as their separate categories. Something similar to [Lightning](https://www.lightningdesignsystem.com/design-tokens/#category-font-size).
