### ISSUE TITLE
Gtihub Action to run unit tests & linting

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/design-tokens#15]
Add a github action that runs tests & linting on push & PR

**Comment by akrifari** [comment]
Hi, can I work on this one?

**Comment by lukasoppermann** [comment]
Hey @akrifari sure, that would be great. Have you done it before?

Just in case you did not, here is a file to "get inspired" by (probably not the best, but it works 😁) https://github.com/lukasoppermann/veare/blob/master/.github/workflows/nodejs.yml

**Comment by akrifari** [comment]
> Hey @akrifari sure, that would be great. Have you done it before?

In the past, I used travis to do CI/CD

> Just in case you did not, here is a file to "get inspired" by (probably not the best, but it works grin) https://github.com/lukasoppermann/veare/blob/master/.github/workflows/nodejs.yml

Thank you, I'll take a look

**Comment by lukasoppermann** [comment]
Great. Github actions are very similar to Travis.

**Comment by akrifari** [comment]
Yeah, same concepts I think

Got a question, which node version do we want to run our actions?

**Comment by lukasoppermann** [comment]
Good question. I actually don't know what would be equivalent to the figma internals.

If you can't find this out either I would just go with 14.11 or .12 for now.
