### ISSUE TITLE
Export button is disabled

### ISSUE THREAD

**Issue by blackshirtdesign** [lukasoppermann/design-tokens#150]
I have never had a problem before and do everything as I always do.

For whatever reason, ONLY THIS prototype does not allow me to export tokens. The button to export is not working.

Any ideas?

![Screen Shot 2021-10-21 at 2 05 39 PM](https://user-images.githubusercontent.com/67355584/138343167-ed0900b9-ee58-4644-a5cc-6166c80d8cf9.png)

**Comment by lukasoppermann** [comment]
Hey @blackshirtdesign this is very hard to diagnose without editing rights. But maybe you can open the console in figma via the command platte (/ or cmd + p) and "open console".

Can you let me know if you see anything when you press the button? Thanks

**Comment by lukasoppermann** [comment]
Hoping this has solved itself. If not please reopen with more info.
