### ISSUE TITLE
Question: Would it be possible to have sync from GitHub?

### ISSUE THREAD

**Issue by edwardbattistini** [lukasoppermann/design-tokens#152]
Thank you so much of this marvellous plugin, 

I was wondering if you had any plans/interests into allowing sync back from github? 

- I have 3 themes in my DS and I find maintaining Figma files for the 3 themes is really time consuming
- Having a way to sync my tokens back to a single "white label" file would really rock
- Sometimes Figma can get out of control with contributors and it's hard to see the differences between live code and FIGMA, Syncing back from code could help starting on strong bases.

Anyway let me know if that something you could consider? or if you have any tips to handle such workflow

THanks

**Comment by lukasoppermann** [comment]
Hey @edwardbattistini,

I do have **interest** in a sync back to Figma. However currently I have not worked on this.

I would love to allow a sync from a w3c token file to text styles, color styles, elevation styles and grid styles. So anything that can be added as a style.

Would you be interested in contributing?
