### ISSUE TITLE
Hex values exported with 8 characters

### ISSUE THREAD

**Issue by lorenzvs** [lukasoppermann/design-tokens#153]
Why is the latest version of the plugin exporting colors with 8 characters?

e.g. `#008799` exports now as `#008799ff`

**Comment by lukasoppermann** [comment]
Hey @lorenzvs this was already discussed here in more detail #151 but in short, it is a `hex8` value, the last two characters are the alpha value.

While it is supported in many browser you can easily convert it to rgb using something like [tinyColor](https://www.npmjs.com/package/@ctrl/tinycolor) to convert it, here is an example: https://github.com/lukasoppermann/design-tokens/blob/main/examples/libs/common/colorToRgbaString.js

**Comment by lorenzvs** [comment]
Thanks for the quick answer. The tokens still work so not an issue at all, it just happened unexpectedly and couldn't figure out why.
