### ISSUE TITLE
Client_payload weight issue 

### ISSUE THREAD

**Issue by joss-jllt** [lukasoppermann/design-tokens#155]
Hey Lukas, thanks for maintaining this plugin!

I have been making requests to a github repo, and it has been working fine, until I tried exporting tokens from a large file (well, not so large, but lots of typography styles). The token object in the request, even minified, weights 142ko (so not that big...)
Still Github throws me a 422 and justifies it by the payload being too large. 

Is it possible for you to increase (or specifiy at least) a limit for your payload when the plugin makes the request?

Thanks a lot for your help!

```
{
  "message": "client_payload is too large.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
}
```

**Comment by lukasoppermann** [comment]
Hey @joss-jllt I will look into it. I am not sure if this is actually the limit or something else is wrong. If you can find out more or figure out a solution please let me know.

Did you try sending the same request via cli to github?

**Comment by FRSgit** [comment]
Unfortunately - I've got the same error on my side. At some point even the compressed payload became just too bit for GitHub to handle (it's 69.2 kB with maximum of 50kB for GitHub actions).

As an quick solution I would propose to add the toggle to "send Design Tokens to url" which would remove things like `extensions` field (and maybe others like `description` as well if they're not necessarily needed). The toggle could be named like "Include Design Tokens-specific data" and be toggled on by default, so it won't be a breaking change.

For me removal of the `extensions` field alon cut done the compressed JSON filesize by roughly 50%.

Will you accept PR of that?

**Comment by lukasoppermann** [comment]
@FRSgit yes that is a great idea. Would you be interested in sending a PR? I think maybe those fields should be toggled individually.

However I am wondering if there is a better way of providing the dat, as 50kb is a very low limit.

**Comment by FRSgit** [comment]
Yea, sure!

Yes, unfortunately Github Actions has a pretty limited API in some regards.

**Comment by lukasoppermann** [comment]
Maybe a future solution could be to enable individual pushes per category. I am not sure this can be automated, but I am thinking basically:
- push colors
- push sizes, etc.

Of course this would have to be optional

**Comment by FRSgit** [comment]
That would work as well, and probably could be automated. Then the github actions script would need to expect "merging" the tokens data instead of replacing them. For sure it's doable. But first it would be good to raise this issue to the GitHub team, maybe it won't be hard for them to come up with a configuration API for setting bigger max payload limit.

I'm not super enthusiastic about this one though, there are many reaaaally old tickets regarding GH actions which weren't resolved for some pretty basic CI stuff (like possibility to look through the artifact files without the need of downloading whole package).

**Comment by lukasoppermann** [comment]
Where is this repo? Happy to open an issue there. :D

**Comment by FRSgit** [comment]
Unfortunately for the dispatches there isn't any 😄 I was talking about the [GitHub's upload-artifact action repo](https://github.com/actions/upload-artifact/issues/14). For the dispatch I think we can raise the issue only via [feedback page](https://support.github.com/contact/feedback).

**Comment by LovreB** [comment]
Hi! Is there any progress on this / other solutions you've found to the issue? Also running into the same issues when trying to send urls to my repo :(

**Comment by kyh** [comment]
Same on my end here, we're just manually exporting for the time being but would love a even smaller compressed version

**Comment by lukasoppermann** [comment]
> Same on my end here, we're just manually exporting for the time being but would love a even smaller compressed version

@kyh any idea how this could work? There is a compression possibility build in that I am sure you use. But how could we improve this?

**Comment by kyh** [comment]
I'm not too sure unfortunately 😞 maybe a couple possibilities:
- if it's unused we could strip out some of the extension metadata
```
        "extensions": {
          "org.lukasoppermann.figmaDesignTokens": {
            "styleId": "S:02f547c85851469d0ee5ac59b8b1f5f6141e00bb,",
            "exportKey": "color"
          }
        }
```
- allow users to import a script as a preprocess step so we can manually remove things we may not need
- remove duplicate styles?

**Comment by lukasoppermann** [comment]
Since version 61 the extension property can be removed when using the standard format.

<img width="631" alt="Screenshot 2023-07-25 at 13 42 19" src="https://github.com/lukasoppermann/design-tokens/assets/813754/cd3fe0dc-5296-4595-a8ca-961268d0e92c">
