### ISSUE TITLE
Exported hex color values wrong in some cases

### ISSUE THREAD

**Issue by tranrb** [lukasoppermann/design-tokens#157]
Hi!

We are having some minor issues with exported color tokens: most are corrects but some are not.

For example, in FIgma, we have `#01A299` but we are getting `#FFA299FF` in the output file.
When `#00B3A6` is correctly exported to `#00B3A600`.

Actually, most of our color palette is ok: there's maybe a pattern with hex colors starting or ending with `01`, or when in the middle (`#xx01xx`). Hope it helps!

Thanks for your awesome work nevertheless!

**Comment by lukasoppermann** [comment]
Thank you for the report. I will look into it and let you know what I find out.

**Comment by claudiozoocial** [comment]
Hi! thank you for your work any updates on this?

**Comment by tranrb** [comment]
Sorry for the late answer (recently changed job)!
I've just tested this issue and everything is now working fine: i can happily close this issue. 👍
