### ISSUE TITLE
Figma board Example?

### ISSUE THREAD

**Issue by sir-captainmorgan21** [lukasoppermann/design-tokens#158]
First. This plugin is awesome! But even with the documentation, its isn't quite clear on how to get the desired results and tokens you want. Do you have an example Figma board to work off of that shows a solid token set?

**Comment by lukasoppermann** [comment]
Sorry, I didn't see this until now. 

I do: https://www.figma.com/file/2MQ759R5kJtzQn4qSHuqR7/Design-Tokens-for-Figma?node-id=231%3A0

It is also accessible from within the plugin: https://github.com/lukasoppermann/design-tokens#design-tokens--demo-file

Hope this helps.
