### ISSUE TITLE
Text styles properties are not converted to individual token if using Standard Format

### ISSUE THREAD

**Issue by zetareticoli** [lukasoppermann/design-tokens#160]
I have this JSON structure automatically exported by Figma:

```json

"font": {
    "textSmall": {
      "type": "custom-fontStyle",
      "value": {
        "fontSize": 16,
        "textDecoration": "none",
        "fontFamily": "Inter",
        "fontWeight": 400,
        "fontStyle": "normal",
        "fontStretch": "normal",
        "letterSpacing": 0,
        "lineHeight": 20,
        "paragraphIndent": 0,
        "paragraphSpacing": 0,
        "textCase": "none"
      }
   }
```

Then, I run the command `style-dictionary build` and this is the result in CSS and SCSS:

```css
:root {
  --undefined-font-text-small: [object Object];
}
```

```scss
$undefined-font-text-small: [object Object];
```

Am I wrong or is it a bug?

Thanks!

**Comment by lukasoppermann** [comment]
No, you are not doing it wrong. Style dictionary does not support this yet. You need to add your own transformer for that.

You can use this example as a starting point: https://github.com/lukasoppermann/design-tokens/blob/main/examples/libs/web/webFont.js

**Comment by zetareticoli** [comment]
Thanks @lukasoppermann.

When I read [this](https://github.com/lukasoppermann/design-tokens#figma-style-design-tokens) I thought it was supported.

**Comment by lukasoppermann** [comment]
Hey @zetareticoli to get this you need to use the "original" token format in the settings. However feel free to create an issue to request individual properties for font styles in the standard format as well.

**Comment by zetareticoli** [comment]
> Hey @zetareticoli to get this you need to use the "original" token format in the settings.

Thanks, it worked. I only have one question: how should I handle units?

**Comment by lukasoppermann** [comment]
What do you mean by this @zetareticoli ?

**Comment by zetareticoli** [comment]
Why values (e.g. font-size) come without 'px' unit?

**Comment by lukasoppermann** [comment]
Hey @zetareticoli I just released the update, so now you can enable "typography" tokens in the standard format.

**Comment by zetareticoli** [comment]
Thank you @lukasoppermann, really appreciate your support
