### ISSUE TITLE
Replace "react-figma-plugin-ds" with internal components

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/design-tokens#162]
The **react-figma-plugin-ds** project is not maintained and creates problems. It needs to be removed.

To remove it all used components have to be integrated.
- [ ] Button
- [ ] Checkbox
- [ ] Select
- [ ] Title
- [ ] Input
- [ ] Label
- [ ] Text

**Comment by ZaidKhan144** [comment]
@lukasoppermann What do you mean by integrated?

**Comment by lukasoppermann** [comment]
Well, they have to be added to this project instead of using them from the dependency. I started this in #163
