### ISSUE TITLE
Option to remove/ignore "extensions"

### ISSUE THREAD

**Issue by e-aubrey** [lukasoppermann/design-tokens#167]
After an update, I noticed the exported json now includes an "extensions" object. Would it be possible in settings or before export to turn off or ignore adding this to the exported file? 

Thanks!

**Comment by lukasoppermann** [comment]
Hey, this is definitely a valid case. Would you like to send a PR for this?

**Comment by bdrtsky** [comment]
No way to remove `extensions` currently?

**Comment by lukasoppermann** [comment]
No. This is why the ticket is still open. Feel free to send a PR.

**Comment by hayawata3626** [comment]
@lukasoppermann 
Maybe this issue can be closed.
ref: https://github.com/lukasoppermann/design-tokens/pull/249/files
