### ISSUE TITLE
letterSpacing missing from the json output

### ISSUE THREAD

**Issue by fitfab** [lukasoppermann/design-tokens#173]
This is the output from `Send design tokens to URL`:
```json
"letterSpacing": {
    "type": "dimension",
    "value": 0
},
```

even though we have a value in the figma file:
<img width="289" alt="Screen Shot 2022-01-11 at 1 41 42 PM" src="https://user-images.githubusercontent.com/286703/149002287-2d6a9651-0bf5-42df-9e00-4c92e14706bd.png">

**Comment by lukasoppermann** [comment]
Hey, this should be fixed now. Please let me know if it works.

**Comment by fitfab** [comment]
@lukasoppermann -- Great! I will test it and let you know.

**Comment by fitfab** [comment]
@lukasoppermann -- it worked. Thank you!

**Comment by lukasoppermann** [comment]
Great to hear it, thank you for the info.
