### ISSUE TITLE
Wrong HEX value is exported

### ISSUE THREAD

**Issue by lavr001** [lukasoppermann/design-tokens#174]
Hi,

I have 2 questions:

1. When I exported a design tokens file from Figma, one color was exported with the wrong hex value (in Figma it was `#010205`, but after I run it through a style dictionary transformer it was `#ff0205` in `_variables.scss`)
2.  All colors in `design-tokens.colors.json` file have an extra ff in the end of each hex value (e.g. the color above was `#ff0205ff`), that ff was removed from each color after I run the json file through a style dictionary, but just wondering why it's happening.

Thank you, Roman

**Comment by lukasoppermann** [comment]
Hey, the FF is transparency. Those are hex8 values. You need to do some custom transformer to convert it. It was already discussed in another ticket, let me find the link.

**Comment by lukasoppermann** [comment]
Hope that helps: https://github.com/lukasoppermann/design-tokens/issues/151

**Comment by lavr001** [comment]
@lukasoppermann  Thank you. Do you know what might be the reason for exporting one wrong hex value?

**Comment by lukasoppermann** [comment]
It's not wrong it's by design. Hex8 includes transparency. The last two characters are a transparency value. Hex8 is the preferred color value in the w3c design token spec

**Comment by lavr001** [comment]
@lukasoppermann I'm referring to my first question. In Figma file one of the colors I'm exporting is `#010205` (black) and in design-tokens.colors.json that color got a wrong hex value of `#ff0205` (red). This is the only color that got a wrong value during the export.

Any ideas why it's happening?

**Comment by lavr001** [comment]
Adding these 2 screenshots to clarify the issue:

<img width="240" alt="figma_black" src="https://user-images.githubusercontent.com/19784835/150412611-1ea5ff19-04a4-4353-aa96-91b9fa6f4a91.png">
<img width="790" alt="design_tokens_black" src="https://user-images.githubusercontent.com/19784835/150412627-bfadbb58-c82a-4aa7-97da-27fbfd41274c.png">

.

**Comment by lukasoppermann** [comment]
Sorry, I missed that. Fix is out, please let me know if this solves the issue. Thank you.
