### ISSUE TITLE
Feature request: Gitlab integration via token

### ISSUE THREAD

**Issue by jahglow** [lukasoppermann/design-tokens#175]
Hello, thanks for your great plugin, is it possible that you add a Gitlab alongside github for an easy integration with an ability to specify a branch to create a merge request to by pushing design tokens? If you could provide guidance on how to do this manually for now - that would be great. Specifying a path to a folder in the repo would also be great

**Comment by lukasoppermann** [comment]
Hey @jahglow I am not using gitlab, so I am missing the experience here, but I am happy to work together with you to solve this.

Technically you can change the type of token to basic or bearer. But maybe you need a specific token or a specific header for gitlab?

Does gitlab have actions, similar to github actions?

**Comment by lukasoppermann** [comment]
Ahh, okay, sounds good.

**-> Closed until more information is available.**
