### ISSUE TITLE
"Accept" Header Not Working

### ISSUE THREAD

**Issue by dgmartin** [lukasoppermann/design-tokens#183]
After trying to trigger a Gitlab webhook and failing I started playing around with the different settings. One change I tried making was updating the value for the "Accept" header. I ended up using Burp Suite to intercept the request and found that the header was not actually getting updated. Based on what I could tell (Sorry, I'm an Android dev not web) it seems this is the problem code is at line 41 of the [urlExport.ts](https://github.com/lukasoppermann/design-tokens/blob/a9e9560c527a8bd15e55554ca102a33e0eefb920/src/ui/modules/urlExport.ts) file:
```ts
  if (exportSettings.acceptHeader !== '') {
    request.setRequestHeader('Accept', 'application/vnd.github.everest-preview+json')
  }
```

It seems it's changing the value when it is NOT empty when really it should change it when it IS empty. The code should probably look like this:
```ts
const acceptHeader = exportSettings.acceptHeader || 'application/vnd.github.everest-preview+json'
request.setRequestHeader('Accept', acceptHeader)
```

Note: For anyone reading this looking for updates on the Gitlab flow see the following tickets:
#181 
#182

**Comment by lukasoppermann** [comment]
This is fixed in #184 thank you.
