### ISSUE TITLE
Empty `dash-pattern` when exporting solid border style 

### ISSUE THREAD

**Issue by Landschaft** [lukasoppermann/design-tokens#188]
I have  a solid [border style](https://github.com/lukasoppermann/design-tokens#borders) `my-border-style` defined. When I export that style, this results in a dash pattern with an empty value:

    "dashPattern": {
        "value": "",
        "type": "string"
    },

This in turn will result in an **invalid SCSS variable** definition of the form:

    $my-border-style-dash-pattern: ;

As a workaround, I am able to define my border style as _dashed_ with dash=0 and gap=0. That way, the export would work, but Figma will display the style as "solid".

**Comment by lukasoppermann** [comment]
Hey @Landschaft, thanks for the issue.

Do I understand correctly, that the solution should be to set dashPattern to `0` if the value is empty?

**Comment by Landschaft** [comment]
In my specific use case I'm not interested in the dash pattern at all since I use a solid border. All I need is (syntactically) valid definition of all the variables.

> As a workaround, I am able to define my border style as dashed with dash=0 and gap=0. That way, the export would work, (...)

This results in the output

     "dashPattern": {
        "value": "0, 0",
        "type": "string"
      },

which in turn will result in (syntactically correct) CSS

     $my-border-style-dash-pattern: 0, 0;

This is okay in my specific use case.

Note that I don't understand how anybody could make use of `my-border-style-dash-pattern` and therefor I'm not sure if this solution will work in any case.
