### ISSUE TITLE
422 error (file is too large) for GitHub sync

### ISSUE THREAD

**Issue by alexhris** [lukasoppermann/design-tokens#191]
Hi, I'm not sure if I have too many tokens (both native Figma and custom ones), but after a while I'm not able to push the changes to our GitHub repo. The message I receive is with 422 error code and the following output in console:

`{message: "client_payload is too large.",…}
documentation_url: "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
message: "client_payload is too large."`

The last json that I was able to push was with 2246 lines and 54.7 KB, which is not too much for a json file. 

Not sure if there's a limit set to the plugin or a general issue (if I hide some of the styles by using "_", it continues to push the file without issues).

Thanks upfront!

**Comment by lukasoppermann** [comment]
Hey @alexhris 

did you use the compress option?

Github does have a limit https://github.com/lukasoppermann/design-tokens/issues/67 so this could be the issue.

Can you export the tokens into a local file or does this create an issue as well?

**Comment by lukasoppermann** [comment]
I am assuming this is just the github limit. If not, please reopen.

**Comment by alexhris** [comment]
Sorry, I didn't receive notifications for your messages. Compress option works for us for now, the problem is that the code updates are unreadable in the pull request. Exporting worked as well, it was only the sync of uncompressed files. Thanks.
