### ISSUE TITLE
Wrong exported letter spacing value

### ISSUE THREAD

**Issue by alvaro-zityhub** [lukasoppermann/design-tokens#194]
Hi! In my Figma project I have the following two label fonts with the following properties:

![image](https://user-images.githubusercontent.com/83757829/158855856-e63adacb-df31-43b9-be61-a1bbd2519408.png)

As you can see the `letter-spacing` property contains the `0.04em` value.
When using the Design Tokens plugin, i'm getting the following `letter-spacing` values for both label fonts:

![image](https://user-images.githubusercontent.com/83757829/158856290-1fe75f67-2754-433a-a87f-a750d3880e4f.png)

I don't understand why i'm getting 0.56 and 0.48 as spacing values when correct is `0.04em`. Any idea about this? Maybe this is something belong to the Figma API?

Thanks! :)

**Comment by lukasoppermann** [comment]
Hey, the issue is, that the letterspacing is turned into pixel by comparing it to the fontSize. 

The problem is that em is not working for other platforms. If you get 0.04em it would be calculated compared to the font-size as well, correct?

**Comment by alvaro-zityhub** [comment]
@lukasoppermann Oh cool ! that's it. Multplying `0.04em` * font-size I'm getting the `letter-spacing` in `px` unit, according to the font size own of the type font.

So In my code, I only have to create my generic theme file taking in account that returned `letter-spacing` values comes in `px` unit (no `em` unit is necessary). 

If designer changes the `font-size` of type font from Figma, and changes the `letter-spacing` value according to the new font size, the Plugin is going to export the new `letter-spacing` value with the new `px` conversion according to the new font size. So I think that's perfect.

From my side this issue can be closed successfully. Thank you very much ;)
