### ISSUE TITLE
Museo Sans Font Weight Support - All font weights are 400

### ISSUE THREAD

**Issue by bryanlopez-ibotta** [lukasoppermann/design-tokens#198]
I created a text style in Figma with Museo Sans at 300 font-weight but when exported it says this and any other text style I define with this font are font-weight "400" which isn't even an option for that font!

**Comment by bryanlopez-ibotta** [comment]
Okay, I see the issue. Museo only uses numbers to describe the weights. We need to add {300: 300, 400: 400}, etc. to https://github.com/lukasoppermann/design-tokens/blob/59c35552d424f4ef69c703063939fd7ebd17490c/src/extractor/extractFonts.ts#L23

I will make a PR.

**Comment by bryanlopez-ibotta** [comment]
#199 should hopefully fix this.

**Comment by lukasoppermann** [comment]
Thanks for the fix.
