### ISSUE TITLE
export design token file: Cannot read properties of null (reading 'r')

### ISSUE THREAD

**Issue by kaitlynhova** [lukasoppermann/design-tokens#205]
## Description

**Figma Version:** 114.6.1

![Screen Shot 2022-05-25 at 9 37 32 AM](https://user-images.githubusercontent.com/5474124/170319834-7b8a70fe-df8a-4f5b-ab62-25f55e1fcc0b.png)

1. select "export design token file"
2. Press "Save & Export" button 
3. See: modal doesn't close and an error code is printed into the console.

**Comment by lukasoppermann** [comment]
If you just go to "Design Tokens > Settings" that is the screen.

**Comment by kaitlynhova** [comment]
Here is the settings screen:
![Screen Shot 2022-05-25 at 10 32 23 AM](https://user-images.githubusercontent.com/5474124/170328485-5145b02d-e4af-4af2-ba0a-fc20b89e1dd0.png)


I don't think I can share the color styles publicly, though. the tokens are named like "Pink/pink-100" though

**Comment by lukasoppermann** [comment]
Hey @kaitlynhova any updates here? Does the problem persist? Can you create an example file with the issue so that I can test it myself?

**Comment by kaitlynhova** [comment]
Thank you for checking in! The problem has persisted but we found a work around by using a different Figma file that works for some reason 🙏

**Comment by lukasoppermann** [comment]
@kaitlynhova that is weird. And you have all colors in this new file as well? No color that was only in the old file that could produce this error?
