### ISSUE TITLE
Support Spring motion

### ISSUE THREAD

**Issue by aloisdeniel** [lukasoppermann/design-tokens#206]
The last Figma release added support for spring animations.

![image](https://user-images.githubusercontent.com/7687231/170526482-164e71eb-e6c3-44d6-9599-face15f213f0.png)

But, if I try to export such an animation, I get an error.

![image](https://user-images.githubusercontent.com/7687231/170526603-0a8c2770-54ff-459b-80ec-594319052ea1.png)

Figma plugin APIs have probably changed which breaks current plugin version!

**Comment by lukasoppermann** [comment]
Hey @aloisdeniel sorry that it takes so long, but I am very busy. However I just wanted to let you know that I can reproduce the issue and will work on a fix.

**Comment by lukasoppermann** [comment]
Short update @aloisdeniel the new release does NOT allow export for spring animations yet. However as a quick fix they are ignored and should not result in an error.

I am working on bringing spring animations into the plugin, it is the next task on my list.

**Comment by aloisdeniel** [comment]
No worries! Thank you!
