### ISSUE TITLE
output [object Object] in _variable.less and _variable.scss

### ISSUE THREAD

**Issue by zhanglun** [lukasoppermann/design-tokens#216]
I got css，less and scss files after I didi `npm run transform-tokens`, It was nice!
But output [object Object] in _variable.less and _variable.scss
<img width="681" alt="image" src="https://user-images.githubusercontent.com/3086358/176088236-807a03ab-8c03-46b9-b36d-6d523e84d281.png">

**Comment by lukasoppermann** [comment]
Hey, which format are you using? Is it the "original (deprecated)" one? What is your setup the transformation? Are you using the default setup from https://github.com/lukasoppermann/design-token-transformer/blob/main/package.json ?

**Comment by zhanglun** [comment]
I followed the steps here [lukasoppermann/design-tokens#transforming-tokens-using-amazon-style-dictionary](https://github.com/lukasoppermann/design-tokens#transforming-tokens-using-amazon-style-dictionary). Is it possible that it is caused by Style Dictionary?

**Comment by zhanglun** [comment]
@lukasoppermann  I think I have figured out the problem.
https://github.com/lukasoppermann/design-token-transformer/blob/main/tokens/design-tokens-example.json was exported with "standard" format.
