### ISSUE TITLE
Typography doesn't export in a transformable way if Fonts included

### ISSUE THREAD

**Issue by derekwsgray** [lukasoppermann/design-tokens#220]
The README suggests (using standard format) that it can export both Fonts and Typography tokens, however the tree structure doesn't seem to be valid (by that I mean, using only style-dictionary transforms alone would not be enough, for web css)

It exports something like this:

```json
{
  "myTheme": {
      "font": {
          "myFontA": {
              "type": "custom-fontStyle",
              "value": {
                  "fontSize": 42,
                  "textDecoration: ...  etc.
               },
               "fontSize": {
                  "type": "dimension",
                  "value": 42
               },
               ... the others
          }
      }
   }
```
Since `myFontA` has a `type` and a `value` key, the other siblings are not picked up as separate tokens and get ignored.

**Comment by lukasoppermann** [comment]
Hey, this is correct. Style dictionary does not support the w3c standard. You will need to create custom transformers for this. That is by design. I am assuming that once the w3c format is finalized and releases style dictionary will implement it as well.

**Comment by derekwsgray** [comment]
Now I'm getting confused... So when your plugin outputs "Standard" format.. it's not really the w3c draft standard.
 
According to StyleDictionary format what you output _should_ be supported: https://amzn.github.io/style-dictionary/#/tokens?id=design-tokens so I'm not sure actually why the individual "fontSize" gets skipped by StyleDictionary... In StyleDictionary format, a group can also _be_ a token itself, while having child tokens.

But according to the Standard, what the plugin outputs above is _not_ valid. In the spec, the way I'm reading it at least, you _cannot_ mix Groups with Tokens: https://tr.designtokens.org/format/#additional-group-properties

Where am I going wrong?

**Comment by lukasoppermann** [comment]
So what is outputted in the Original (outdated) mode, should be supported by style dictionary.

What is output in standard mode is not. It is by now also not according the standard anymore, as they updated. I will hopefully in the next days/weeks have time to refactor standard to align with the specs.

**Comment by lukasoppermann** [comment]
What you have written there in the code is not valid. However I can not reproduce it. For me it is a normal composite token: https://tr.designtokens.org/format/#composite-design-token

**Comment by derekwsgray** [comment]
I figured out why you're not seeing it. You have to turn OFF auto prefixing. 
![image](https://user-images.githubusercontent.com/5737686/187946736-b01fc2a8-97e3-4ba5-8a8a-aebbfcc753e2.png)

So I'm not sure the best way to avoid generating invalid standard format... we definitely don't want to turn on the prefixing because we want '<product>-<theme>-' to come first in the token name.

**Comment by derekwsgray** [comment]
I've updated the title to reflect the special case. Should be re-opened.
