### ISSUE TITLE
Variants are being ignored for custom tokens

### ISSUE THREAD

**Issue by derekwsgray** [lukasoppermann/design-tokens#221]
As someone not super familiar with Figma, I was creating a bunch of custom tokens. Under a `_tokens` frame, I added a component, name it, say, `border/mytheme-border-thin`. To create the next one (e.g. `border/mytheme-border-medium`, I naturally Copy & Paste the first one and drag it below, and rename it. BUT this creates a variant, not a new component. It takes a few steps to convert that to a Component and really takes a lot of clicks if you have a lot of tokens to create.

Is that a possibility to support variants?

Thanks!

**Comment by lukasoppermann** [comment]
Hey, variants should already be supported. Does it not export those for you? 

If not, can you please:
1. make sure it does export a normal `border//mytheme-border-thin` component without variants
2. if it does, provide an example figma file I can look at?

**Comment by derekwsgray** [comment]
I realized later that the docs indicated variants _were_ supported, so I've updated the title of this issue to reflect that it's a bug.

**Comment by derekwsgray** [comment]
Here is a basic file with 1 component, and 1 variant (created by keyboard copy/paste of the component). The component exports as a custom border token, the variant does not.
https://www.figma.com/file/XVsv0TuECvIKVcd5d0SASr/DT-Variant-Test?node-id=0%3A1

**Comment by lukasoppermann** [comment]
Hey @derekwsgray, this is not a `variant`, it is an `instance`. `Instances` are not supported.

To speed up your workflow you could do the following:
1. Create a frame (not a component)
2. Duplicate this and create all other variations you want
3. select all and create multiple components via the dropdown and "create multiple components"
<img width="325" alt="Screenshot 2022-08-15 at 20 50 47" src="https://user-images.githubusercontent.com/813754/184697318-799f4b2d-0d6f-4306-a96c-0236fa0ec540.png">

Closing this as it seems to be all according to design. If you feel there is still something not working as it should, please reopen.

**Comment by derekwsgray** [comment]
Ah, sorry for my ignorance, and thanks for the tip.

**Comment by lukasoppermann** [comment]
Hey @derekwsgray no worries, variants and instances are a very close concept I totally understand the confusion.
Hope this helps in any case.
