### ISSUE TITLE
Can Design toke can push to private repos?

### ISSUE THREAD

**Issue by pukingrainbows** [lukasoppermann/design-tokens#222]
What configuration do private repos need to have in order to receive the event on their workflow? I received 404 each time I try to use a Personal Github and the organization repo. 

Thank you for such a great project.!!

**Comment by pukingrainbows** [comment]
Ohh after literally 3 hours lol, I found out that when you created your personal access token on github, on the plugin when selecting the type of auth, you shouldn't pick `Github token`, it has to be `bearer token`!!!!! 

I think the documentation is a little misleading. Or at least that's how worked for me

**Comment by lukasoppermann** [comment]
Hey @pukingrainbows, this is not how it is supposed to work.

I just tried it and for me it worked. How did you create the token?
