### ISSUE TITLE
Update Figma styles from .json

### ISSUE THREAD

**Issue by markjharvey** [lukasoppermann/design-tokens#233]
While this plug-in is great for the workflow of:

- Create/tweak/update styles in Figma
- Export to .json for Styledictionary

This creates a strain and bottleneck for larger changes. To change 20 color styles requires a lot of work right now, as Figma is the source of truth, and is very slow.
It would be really good to have the reverse workflow as well, for example:

- If you want to change an entire color family, you can do that much easier in the .json. There are online color tools that can generate entire palettes and output to .json.
- From the styles in the .json, upload and update the Figma color styles.

**Comment by lukasoppermann** [comment]
Hey, this is a very interesting idea I have thought about as well. However I am currently waiting to see what will be announced at schema 2022 on 16.11.22

There is supposed to be some design token stuff coming, so we will see how this affects everything.

**Comment by edwinmesmerise** [comment]
I was also interested in two way synchronisation between Figma and JSON. I don't know how you'd resolve custom tokens created in JSON that are not in the Figma file unless you can generate components from the JSON, that would be amazing.

**Comment by lukasoppermann** [comment]
Hey, it is even more likely that we get some kind of native token this year. There has been semi-official communication about this.

I will not add this functionality as it is a lot of work and would only work for styles, sorry.
