### ISSUE TITLE
License of example figma file

### ISSUE THREAD

**Issue by ccouzens** [lukasoppermann/design-tokens#238]
Hi,

Thank you for this plugin. I find it useful.

I would like to know if I have permission to redistribute the API dump of the example Figma file in my repo?
https://www.figma.com/file/2MQ759R5kJtzQn4qSHuqR7/Design-Tokens-for-Figma

This repo is MIT licensed, but I don't think that applies to the file hosted on Figma. [My repo](https://github.com/ccouzens/figma-rust) is also MIT licensed.

I would like to use the Figma API dump of [the file](https://www.figma.com/file/2MQ759R5kJtzQn4qSHuqR7/Design-Tokens-for-Figma) as a test case in my project.

**Comment by lukasoppermann** [comment]
Hey, sure, feel free to do that.

**Comment by ccouzens** [comment]
Thanks :)
