### ISSUE TITLE
Latest version issues

### ISSUE THREAD

**Issue by ianvieira** [lukasoppermann/design-tokens#244]
On Figma, seems like we have a new version since 5 days ago, this version has a few breaking changes and is not on the master, which leads me to think it might be an accidental release (as it's not on the release log or master branch). It seems like the `w3c` branch was released and is not merged to master yet.

I could identify at least 3 breaking changes on this version:
1. The default format now is the latest W3C and not the one used on prior version (it's ok as you can select to use the prior one)
2. The `typography` token is no longer generated as it was before on W3C deprecated format. Looking at the [code](https://github.com/lukasoppermann/design-tokens/blob/744acc85d09d4143822f1f374721f3c3f313daf7/src/utilities/prepareExport.ts#L19) it seems an intentional change but it's also a breaking change.
3. In the new W3C font format, we don't receive the letterSpacing, although it's on the [transformer](https://github.com/lukasoppermann/design-tokens/blob/744acc85d09d4143822f1f374721f3c3f313daf7/src/transformer/standardTransformerV2.ts#L79)

Is possible to clarify on what is expected to this change and if it's possible to have the W3C Deprecated format as before the last release? I believe this can generate a breaking change on several applications and even migrating to the new format is not possible due to the lack of letterSpacing.

Thank you!

**Comment by lukasoppermann** [comment]
Hey @ianvieira this is somewhat accidental, yes. The release process of figma plugins is to say it mildly, not ideal.

I want to merge the w3c branch soon/

1. Yes, as you said, can be changed.
2. Have to look into this, this has been in the works for longer, but I think this is because of the w3c standard,
3. Will look into it, thanks

**Comment by ianvieira** [comment]
@lukasoppermann Thank you very much for the fast response! Is it possible to "rollback" to the master version until the work on the w3c branch is not "finished", as it's not possible to opt-out of it and maintain compatibility with what was available before?

**Comment by lukasoppermann** [comment]
Hey, I tried it now. However I am unsure as having the dev version on my mac somehow messes it up sometimes. Can you please verify if it was rolled back and let me know? Thanks. 🙏

**Comment by ianvieira** [comment]
I believe it's broken. When trying to export to file you have this error:
```
VM177:640 Uncaught TypeError: sr[n.tokenFormat] is not a function
    at <anonymous>:640:24831
    at Array.map (<anonymous>)
    at cr (<anonymous>:640:24806)
    at onSubmit (<anonymous>:650:739)
    at Object.Te (<anonymous>:2:84110)
    at $e (<anonymous>:2:84264)
    at <anonymous>:2:104124
    at Ur (<anonymous>:2:104218)
    at Dr (<anonymous>:2:104632)
    at <anonymous>:2:110060
```

**Comment by ianvieira** [comment]
Now the export worked properly @lukasoppermann and I have the typography field back :)
