### ISSUE TITLE
Looking for feature requests -Building a design to code tool

### ISSUE THREAD

**Issue by levirtevs** [lukasoppermann/design-tokens#245]
Hi @lukasoppermann 

I have been working on an experimental project that generates readable code to be used by developers. It works cross framework and have a look here for more.

It is called ui-editor
https://github.com/imvetri/ui-editor

The concept scales to work as a design tool. However I'm looking for feature request which I can build. Would you be interested to collaborate on it?

**Comment by lukasoppermann** [comment]
Sorry I don't get how this is related to this plugin for Figma.

**Comment by levirtevs** [comment]
@lukasoppermann this is not related to figma, this is an open source competitor for figma. I have built the core for a designing tool that can generate readable debuggable code in reactJS, angular, svelte.

**Comment by lukasoppermann** [comment]
What I am say is that [this repo](https://github.com/lukasoppermann/design-tokens) is for a Figma plugin.

**Comment by levirtevs** [comment]
okay got it. I thought you would be interested that's why dropped a note.
