### ISSUE TITLE
minimal figma requirements to export color tokens

### ISSUE THREAD

**Issue by daniel-clover** [lukasoppermann/design-tokens#250]
Hey!
Sorry if this isn't the appropriate place for this, but here goes:
I've a bunch of Figma files, about 30% generate tokens.
I understand from the README that to export radii, etc. one needs to follow the structure provided, but it was my understanding that color token creation doesn't require any special formatting.
But that hasn't been my experience. 
I'm an engineer, not a designer and have very little experience working with Figma, but how can I instruct our designers on how to format their color files so that they will export as expected.
Thanks for your attention!
Also, the plugin and transformer are amazing!

-Daniel

**Comment by lukasoppermann** [comment]
Hey Daniel,

I hope this is no misunderstanding, but the Plugin does NOT export colors that are using in components / designs automatically.

To export colors as design tokens either use the new variables with the standard format, or use color styles in figma, those get exported as well.

Does that make sense?

PS: You may have seen this, but if you are interested in transformers, this may interest you as well: https://github.com/lukasoppermann/style-dictionary-utils

**Comment by daniel-clover** [comment]
Hey Lukas,

Yes, this makes sense now!
Thanks so much for your help.

I will check out the `style-dictionary-utils`, is it to work with your https://github.com/lukasoppermann/design-token-transformer or is it an alternative?

Thanks again and have a great weekend!

**Comment by lukasoppermann** [comment]
The `style-dictionary-utils` are also for style dictionary so you can easily use them together with the other transformers. It is a more streamlined package, design-token-transformers is more of an example repo.
