### ISSUE TITLE
Version 61 not working

### ISSUE THREAD

**Issue by FrankiYu** [lukasoppermann/design-tokens#251]
Clicking on any of the menus does nothing, it keeps prompting 'Running Design Tokens". Does any ways to use Version 60 in Figma？

**Comment by lukasoppermann** [comment]
Can you please open th console CMD + option + I and send a screenshot of the error you get?

**Comment by lukasoppermann** [comment]
Hey @FrankiYu I think I found the problem. I will ship a fix asap and let you know.

**Comment by lukasoppermann** [comment]
Should be fixed in 62, please reopen with details if you still experience the issue.

**Comment by FrankiYu** [comment]
@lukasoppermann Please see my screenshot. Thank you!
![WX20230725-134406@2x](https://github.com/lukasoppermann/design-tokens/assets/5143201/710a7ea0-5fd9-4c59-969e-647abfe64b87)

**Comment by FrankiYu** [comment]
Locate the file
![WX20230725-134731@2x](https://github.com/lukasoppermann/design-tokens/assets/5143201/795f2b08-a154-4adf-9ac2-55ac694cfd43)

**Comment by lukasoppermann** [comment]
What value do you have in your design tokens? Its about numeric values, as it says something about `Unterminated fractional number`.
