### ISSUE TITLE
Bug: Fails to export for some files

### ISSUE THREAD

**Issue by ryanzec** [lukasoppermann/design-tokens#252]
When I load this template:

https://www.figma.com/community/file/854767373644076713/Primer-Web

and then attempt to using Design Tokens to export tokens, clicking `Save & Export` does nothing. When I try in the web application, I see this specifically after clicking that button:

![Screen Shot 2023-07-24 at 6 12 35 AM](https://github.com/lukasoppermann/design-tokens/assets/444206/adde2eac-d40e-48a2-8911-7ef0107fb2e2)

I attempt both token formats with the same result.

I know if I deselect everything when exporting from other Figma files, I get the same effect and I assume that is because no tokens are found however with this Figma template, there are local styles as far as I can tell so it seems weird that would be the issue here but not sure.

It would probably be nice if the export is failing because no tokens are found that was indicated to the user some how.

**Comment by lukasoppermann** [comment]
Let me know if the issue persists.

**Comment by ryanzec** [comment]
So it is better however I seem to have to click on the `Save & Export` button twice to get the no tokens to export message, not a big deal but just figure I would let you know

**Comment by lukasoppermann** [comment]
Hmm, I didn't notice, but you are right. This is weird. I'll have to investigate. If you get an idea why, please let me know.

**Comment by lukasoppermann** [comment]
Should be fixed now.
