### ISSUE TITLE
"No Tokens found" error when exporting with any selections

### ISSUE THREAD

**Issue by DanielTamkin** [lukasoppermann/design-tokens#256]
Hey @lukasoppermann! Thanks for this fantastic plugin.

When running the plugin currently - with any permutation of types included in export - seeing a "No tokens to export!" Error:

![image](https://github.com/lukasoppermann/design-tokens/assets/9532762/bbaae4f0-c43c-4aa9-a35a-33d5ff8240d4)

Previously was receiving an export of selected types.

**Settings:**
![image](https://github.com/lukasoppermann/design-tokens/assets/9532762/34a338db-3349-48a5-a946-d381110be88a)

**Comment by lukasoppermann** [comment]
I'll look into it later today. Sorry for the issue

**Comment by DanielTamkin** [comment]
Thanks @lukasoppermann! After some testing it looks like https://github.com/lukasoppermann/design-tokens/commit/985b64abbdedba8f6024583d7ca064d0dd0b46df is the last tip that exported successfully. We could revert up to (but not including)  https://github.com/lukasoppermann/design-tokens/commit/985b64abbdedba8f6024583d7ca064d0dd0b46df while the issue is investigated? 😄

**Comment by lukasoppermann** [comment]
Hey, yeah I think I already know what the bug is. But I am not at my Mac so I can not fix or release atm.

**Comment by lukasoppermann** [comment]
Hey @DanielTamkin I hope I fixed it now. 😬

**Comment by DanielTamkin** [comment]
> Hey @DanielTamkin I hope I fixed it now. 😬

Looks like it! Thanks @lukasoppermann 😄
