### ISSUE TITLE
Recent update breaks export variables

### ISSUE THREAD

**Issue by ryanzec** [lukasoppermann/design-tokens#265]
With the latest version, I am no longer able to export tokens when I include variables, I just get this error:

![Screen Shot 2023-08-14 at 7 23 55 AM](https://github.com/lukasoppermann/design-tokens/assets/444206/2d52ac42-8a43-46dc-89cf-948c06ee60ef)

I tried both enabling and disabling the new mode reference feature.

**Comment by ryanzec** [comment]
This seems to be related this this change:
https://github.com/lukasoppermann/design-tokens/pull/263/files#diff-ebe8de5eee60114c6d10956453c31e12c53c196abfeca396733d76a1d52465f3L261
I believe the escaping is require in that context (my regex is not the best but changing it back allow me to export variables again).

**Comment by ryanzec** [comment]
It does seem like the lint thinks those are not needed so not really sure what is going on with it.

**Comment by ryanzec** [comment]
Ok, so it seem like one of the character should be escape but all escape was removed, it seems like this regex works : `/^{[\w\s.\-_/@+&:]*}$/` : and passes linting

**Comment by lukasoppermann** [comment]
Just published the change, can you verify if it works?

**Comment by ryanzec** [comment]
Yea, that latest version seems good
