### ISSUE TITLE
About typography

### ISSUE THREAD

**Issue by hayawata3626** [lukasoppermann/design-tokens#266]
@lukasoppermann 
I want to understand the necessity of the `typography` property([ref](https://github.com/lukasoppermann/design-tokens#figma-style-design-tokens)). It seems similar to `font`, but what are the use cases where it proves beneficial? I feel that font alone should suffice, and I've been intentionally removing typography using the [design-token-transformer](https://github.com/lukasoppermann/design-token-transformer). Is this approach correct?

**Comment by lukasoppermann** [comment]
A `text style` by default is a composite token, meaning a token that consists of multiple tokens itself.

The `typography` option allows you to also export individual properties. This can be helpful as figma does not yet allow you to define e.g. just the `font-weight` as a property.

Basically with this option you get all the tokens that make up the composite token as individual tokens as well.

**Comment by hayawata3626** [comment]
@lukasoppermann 
Thank you, I understand. I will close this issue.
(I apologize, maybe I should have discussed this in the discussion section.)

**Comment by lukasoppermann** [comment]
All good, don't worry about it. Fine here as well. 👍
