### ISSUE TITLE
Issue with exported JSON

### ISSUE THREAD

**Issue by lunik2** [lukasoppermann/design-tokens#271]
Hi! We're having an issue with the JSON structure when we export it and want to use it further in our designs. There is an object called "mode 1" that appears out of nowhere. the frustrating part is, it arbitrarily contains part of the tokens object and breaks up the hierarchy in an unfortunate way. Any way we can control this, or any idea why this happens? thanks!

![Bildschirmfoto 2023-09-12 um 11 33 07](https://github.com/lukasoppermann/design-tokens/assets/34686543/c49289ee-f619-4797-b20c-50ff48e9aa44)
[design-tokens.tokens_new.json.zip](https://github.com/lukasoppermann/design-tokens/files/12584801/design-tokens.tokens_new.json.zip)

**Comment by caoimghgin** [comment]
Might consider using modes in Figma variables rather than defining light/dark within a single mode?

**Comment by andrewpucci** [comment]
@lukasoppermann  I believe that #273 and #274 are duplicates of this issue. I am also having this same problem.

To me, it looks like any variables that are referencing another variable get put into the redundant mode in the hierarchy. In my example below, all of these tokens should be in `color.default.component.logo.company` but there is one that references other variables that has another mode injected into the hierarchy for unknown reasons, which becomes `color.default.default.component.logo.company`.

<img width="556" alt="image" src="https://github.com/lukasoppermann/design-tokens/assets/3422499/3fae3e14-4d89-45ee-b204-73e58383210d">

**Comment by lukasoppermann** [comment]
This should be fixed thanks to @jonbrooks in the latest release, if so, please comment and close. 🙏
