### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by laraamadeo** [lukasoppermann/design-tokens#286]
I'm working in a big file with more or less 300 styles. When clicking to 'Export', nothing happens. However, in a file with less styles, it works. This is the error showing
<img width="379" alt="image" src="https://github.com/lukasoppermann/design-tokens/assets/126255862/4d391c14-c86f-4e31-a849-d89e6fbf8ab6">

**Comment by katywatkins** [comment]
I've just run into what seems very similar, if not the same. Nothing happens on export, but there's a very similar error in the console:
<img width="901" alt="image" src="https://github.com/lukasoppermann/design-tokens/assets/1926679/8056eb46-8666-46f4-b984-151f5a6fd5ed">

**Comment by katywatkins** [comment]
Follow up - turns out the error I ran into above was caused by a mode name that included parentheses. Changing the name fixed the problem.

**Comment by lukasoppermann** [comment]
Hey @laraamadeo we would need to work on narrowing in on the issue:

Can you send me a copy of all your styles? Is this possible? E.g. by exporting a Figma file and attaching it/sending it via email / creating a new file with only the styles and sharing it with me?

1. Do you export variables?
2. Do you have any styles with images / gradients / etc?
3. Do you have any styles or variables with special characters in the names?

**Comment by burn2delete** [comment]
I seem to also have this issue and my variable names have both spaces and parentheses.

**Comment by burn2delete** [comment]
I was able to resolve my issue.

I updated my collection names to avoid any special characters. I also updated the plugin to support name conversion for the variable values, which is required when referencing other variables.

https://github.com/lukasoppermann/design-tokens/pull/301
