### ISSUE TITLE
Variables export not working.

### ISSUE THREAD

**Issue by UgoJau** [lukasoppermann/design-tokens#292]
Hello, 
i'm trying to export variables but it seems to have a problem.
Maybe I missed something.

It works when I'm trying with a file and only primitives.
<img width="173" alt="Capture d’écran 2023-11-21 à 10 39 13" src="https://github.com/lukasoppermann/design-tokens/assets/63340174/0d6d7678-cb9c-48b0-b73a-c5417996658b">

but as soon as I try with all it freeze on Export
<img width="560" alt="Capture d’écran 2023-11-21 à 10 40 54" src="https://github.com/lukasoppermann/design-tokens/assets/63340174/dde11160-6f06-439c-bada-ed722e3701d7">

Thanks for your help

**Comment by lukasoppermann** [comment]
Hey, this can have many reasons. could you open the console (cmd + shift + i) and copy the error message?

There may be a naming issue with one of the tokens on the other collections. Did you try if both of them lead to an error?

**Comment by lukasoppermann** [comment]
I would guess the percentage `%` sign is possibly the issue.

**Comment by lukasoppermann** [comment]
Should be fixed, reopen if it persists.

**Comment by reconfine** [comment]
Confirmed - removing the % symbol resolved the issue. Thanks :)
