### ISSUE TITLE
Font weight is wrongly detected as font style when generated as SCSS and CSS

### ISSUE THREAD

**Issue by glsee** [lukasoppermann/design-tokens#55]
Imagine I have this text style with "Extra Bold"
![Screenshot 2020-11-27 at 3 51 34 PM](https://user-images.githubusercontent.com/457429/100424352-6f126100-30c8-11eb-9e93-39b579a392df.png)

When using the Inspect feature in Figma, the equivalent CSS codes provided by Figma is (see how to the "Extra Bold" font style in Figma UI is translated as `font-weight`):

![Screenshot 2020-11-27 at 3 54 40 PM](https://user-images.githubusercontent.com/457429/100424927-463e9b80-30c9-11eb-8125-0c1cc4ffdd55.png)

 But when I do `npm run transform-tokens`, the following codes are generated:

```scss
$headline-font-style: Extra Bold;
```

<img width="409" alt="Screenshot 2020-11-30 at 2 36 01 PM" src="https://user-images.githubusercontent.com/457429/100576580-619fe580-3319-11eb-9d46-7984e658a08e.png">

**Comment by lukasoppermann** [comment]
Hey @glsee, very good catch. 👍 

This seems to be an issue with the PluginApi where it only returns the style as e.g. "Extra Bold". I am investigating if there is a fix. If you are using a condensed font it is not shown at all, even in the inspector. I will file a bug with Figma concerning this.

I am not sure if a matrix to get the correct values would be feasible, as the naming convention is not very standardised. If you have any insight on this, please let me know.

**Comment by lukasoppermann** [comment]
[According to Jonas from Figma](https://figmaplugins.slack.com/archives/CHPTY6TFD/p1608156495243200?thread_ts=1604525949.417000&cid=CHPTY6TFD) they just use a mapping table for the API.

```js
{"thin", 100},
{"extralight", 200},
{"light", 300},
{"normal", 400},
{"medium", 500},
{"semibold", 600},
{"bold", 700},
{"extrabold", 800},
{"black", 900},
```

This means they are missing the values: "Super", "Heavy", "Demi Bold" as well as "Condensed" & "Extended"

So to get up to what they are doing, a simple mapping table could help. This could include `condensed` & `extend` as well.
