### ISSUE TITLE
Getting blank list on plugin while exporting json file

### ISSUE THREAD

**Issue by dghosh** [lukasoppermann/design-tokens#60]
Getting blank list on plugin while exporting json file. This is the file I am trying to run it on https://www.figma.com/file/eteQ8PXhfQORP09r5XbiPG/TestingDesignTokenExport in case it helps to debug? I am wondering if this is because figma's file structure has changed in json? I am wondering if line 19 in buildFigmaData.ts needs to be just figma.document.children instead ? Purely basing this on the Figma API call though as the response looks like:

{ components: {...}, document: {id: "1", children: [{..}]...}, name: "blah",...}

**Comment by lukasoppermann** [comment]
Hey @dghosh,

to figure out the problem, let me ask two things first:

1. What are you trying to export? It does not look like you have any `styles` set up in Figma (or is this a limitation from the view only project?)
2. If you are trying to export anything like border radii, etc. you need to include the elements in a `_tokens` frame.

**Comment by dghosh** [comment]
Think that might be a limitation of the view only mode. I renamed the frame to _tokens and still no luck! All I get is [] in the downloaded json file.

![image](https://user-images.githubusercontent.com/1861503/102642727-09107b00-4156-11eb-92e4-3cec2d630a88.png)
![image](https://user-images.githubusercontent.com/1861503/102642806-204f6880-4156-11eb-974f-546e336c2fac.png)

**Comment by dghosh** [comment]
@lukasoppermann given you edit access!

**Comment by lukasoppermann** [comment]
Hey @dghosh,
I fixed the file so that it works. The parent frame needs to have the `_tokens` name.

Obviously the docs are not easy enough to understand. Would you maybe have some suggestions how I can improve them, to make it easier to understand?

**Comment by dghosh** [comment]
Ah ok thanks! Went through the reader again and it explains what you have done in renaming the frame. But would be great if you could add some example screenshots of Figma file setup with different combinations and show what the JSON output is, perhaps? Also perhaps some guidance on the plugin too around naming of frames would be helpful I think.

**Comment by lukasoppermann** [comment]
Hey @dghosh I updated the docs and added more descriptions for the token creation.

I also added one image doe the sizes tokens (I will add more later).

https://github.com/lukasoppermann/design-tokens/blob/main/README.md#sizes--spaces

Please let me know if this makes sense or if you think there is something missing.

Cheers

**Comment by dghosh** [comment]
Hi @lukasoppermann this looks good, thanks! Is there a way to get the sizes and borders(or any combination of custom tokens) for any single Frame, Rectangle or Main Component? For example - how can i get the border info along with the size for the 3 shapes in your example file https://www.figma.com/file/2MQ759R5kJtzQn4qSHuqR7/Design-Tokens-for-Figma?node-id=1260%3A44

**Comment by lukasoppermann** [comment]
Hey @dghosh,

this is currently not possible. It would mean that you would always export all properties or would have to use complex naming schemes. 

The best way would be to create 3 frames with similar names like `sizes/small-box`, `radii/small-box`, etc. and work with this.

A potential future option would be to allow users to disable the category prefix e.g. `sizes`, but this could lead to overwriting issues, which would need to be handled somehow or would just have to be accepted.

**Comment by dghosh** [comment]
Perhaps the user specifies which custom tokens to export via the plugin menu and not via naming of the frames? This way if I select sizes and borders then it exports both those info along with other style tokens that get exported by default.

**Comment by lukasoppermann** [comment]
Hey @dghosh can you elaborate on your idea? I think I don't quite understand it.

**Comment by dghosh** [comment]
I am thinking something like this in the settings.

![Uploading 16097633064064104821944256521784.jpg…]()

**Comment by dghosh** [comment]
![IMG_20210104_123138](https://user-images.githubusercontent.com/1861503/103535554-d28e6c00-4e88-11eb-949f-8cc92da4c9a1.jpg)
I am thinking something like this in the settings - allow the users to select which custom token(s) to export

**Comment by lukasoppermann** [comment]
And this would mean that all frames (or maybe all frames with a `_token` prefix) would export the selected types?

But how would a user go about creating border-only tokens? E.g. I want to have my size tokens and I want to have a `border-active` token. This would necessarily have a size, but I don't want it to be a size token. How would you solve this?

**Comment by dghosh** [comment]
So by the fact that the size and border option are ticked in the settings - it would export all the size and border properties for all frames. The output would be like this for two frames:

```
{
 "borders": {
    "frame1": {
       "category": "border",
       ....
    },
    "frame2": {
       "category": "border",
       ....
    }
  },
  "sizes": {
    "frame1": {
       "category": "size",
       "value": 100,
       ....
    },
    "frame2": {
       "category": "size",
       "value": 80,
       ....
    }
  },
  "frame1": {
    "category": "fill",
    "comment": null,
    "value": "rgba(195,62,62,1)",
    "type": "color"
  },
  "frame2": {
    "category": "fill",
    "comment": null,
    "value": "rgba(62,99,195,1)",
    "type": "color"
  },
  "dropShadow": {
    "dropEffect1": {
       "category": "effect",
       "radius": {
          "value": 4,
          ....
        },
        .....
    }
  }
}
```

**Comment by lukasoppermann** [comment]
The issue I see is, that if a users has a frame `sizes/10` and a frame `borders/red` she will get:

```json
"borders": {
    "red": {
       "category": "border",
       ....
    }
},
"sizes": {
    "10": {
       "category": "size",
       "value": 10,
       ....
    },
    "red": {
       "category": "size",
       "value": 25,
       ....
    }
  },
```

**Comment by dghosh** [comment]
right i see. my idea was based on that you wouldn't need to have any naming conventions required for the frames. anything on a page or anything inside a "_tokens" frame is parsed. Is there a use case where you wouldn't want "red" inside the sizes? 
For example if i am designing a website landing page which has header, content and footer frames. I would want to export all properties(sizes, borders etc.) of all the frames? Unless i am missing something here! :)

**Comment by lukasoppermann** [comment]
Hey, I think you may be using the plugin in a different way.

Are you trying to parse design tokens that are used on components?

The main idea of this was to basically build and extract the "library" of design tokens. To this end you would normally only want one aspect per token and have control over the naming.

So yes, you would want to define the e.g. "small-radius", "big-radius" and "bubble-radius" and only have the radius in there, no size, no color, nothing else.

This "variable" would be used when you spec a component. You could then add and arrow with "small-radius" in your spec document to show which token to use. Like visualized here: https://images.ctfassets.net/5dfliyp93yzg/3OKs0KcjOOWfKl6tjqX5vw/0e82373a96f163030a0e8740d3528344/Specs-between-components.jpg?fm=webp&w=2000

**Comment by dghosh** [comment]
Thanks for the explanation! I will go away and do bit more research on design tokens :)

**Comment by lukasoppermann** [comment]
Hey @dghosh I hope this didn't come over as dismissive or something. 

I actually wrote a post about design tokens, maybe this is interesting for you: https://vea.re/blog/design-tokens-what-are-they-and-how-will-they-help-you

It sounds to me like you are trying to extract values for specific components used in a design, straight from the design. This makes sense, but is I think a different use case than creating "design tokens" for a design system.

But please feel free to correct me if I misunderstand what you want to do.

**Comment by dghosh** [comment]
No not at all - i am pretty new to the design tokens concept so appreciate any help and pointers. And yeah I was more coming from a developer hand off point of view - so the developers have the right properties for all the elements/components that are part of the design. 
The vision we have in my team is that we can potentially use design tokens to layout all the properties for each component of the design for a seamless handoff to developers. So any pointers around this would be appreciated! :)

**Comment by lukasoppermann** [comment]
> The vision we have in my team is that we can potentially use design tokens to layout all the properties for each component of the design for a seamless handoff to developers. So any pointers around this would be appreciated! :)

This is generally the idea. However, until Figma natively supports design tokens, this will not be possible with handoff.

The best approach I know currently would be:
1. Create design tokens with this plugin and export them to json
2. Create your components and (yes sadly manually) spec them, writing the name of the tokens next to the component like in the visualisation I added above: https://images.ctfassets.net/5dfliyp93yzg/3OKs0KcjOOWfKl6tjqX5vw/0e82373a96f163030a0e8740d3528344/Specs-between-components.jpg?fm=webp&w=2000

If you find any other way, please let me know. 😉
