### ISSUE TITLE
Third party contributions?

### ISSUE THREAD

**Issue by NoobsArePeople2** [lukasoppermann/design-tokens#62]
Hello,

My team is considering using this plugin and I'd like to know if you will accept contributions (new features, bug fixes, etc) from external users like us?

Thanks.

**Comment by lukasoppermann** [comment]
Hey Sean,

yes I am happy to accept contributions.

Bugfixes always, new features as long as they fit somewhat into the idea of the plugin and don't have a negative impact on other features as well. 

If you are planning on sending a PR for a feature, it is best to first create an issue with the feature idea and maybe a use case (if it is not obvious). Once we discuss an implementation direction you would send a PR and I will happily merge it.

I hope this answers your questions. Have a great day.

**Comment by NoobsArePeople2** [comment]
Perfect! Thanks!
