### ISSUE TITLE
Update design token transformer to create a PR instead of committing straight away

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/design-tokens#80]
- https://github.com/marketplace/actions/create-pr

The idea here is that instead of overwriting the design tokens here: https://github.com/lukasoppermann/design-token-transformer the github action should create a PR that allows manually checking the changes on github before merging.

**Comment by evanroane** [comment]
Hey @lukasoppermann I'm interested in working on this. Could you share more about what you have in mind? I'd be sad if I dug into this work and wound up building the wrong thing.

**Comment by lukasoppermann** [comment]
Hey @evanroane, thank you for picking this up.

The idea here is that instead of overwriting the design tokens here: https://github.com/lukasoppermann/design-token-transformer the github action should create a PR that allows manually checking the changes on github before merging.

Does this make sense?

**Comment by lukasoppermann** [comment]
Fixed by @matthewlyle
