### ISSUE TITLE
How does the naming convention work?

### ISSUE THREAD

**Issue by mwargan** [lukasoppermann/design-tokens#81]
I may be completely misunderstanding something, but I'm confused on two fronts. For one, it seems Amazon specifies a specific naming convention thats required to make "transforms" work, but this plugin doesn't seem to enforce that, right?

Secondly, in the readme example, the outputted fonts have, very nicely, a prepended "--font-" to them. This doesn't seem to be the default behaviour though. Are we supposed to put all our Figma font styles in a "fonts" folder? The Figma example you provided (albeit its for spacing) doesn't seem to have that naming convention.

**Comment by lukasoppermann** [comment]
Hey @mwargan,

1. Style dictionary has a specified structure that you can use to transform it. However you can customize this in the config file (the example in the transformer shows that https://github.com/lukasoppermann/design-token-transformer/blob/main/config.json)

2. For styles you need to prefix the names e.h. `font/` to get this. This is specific to figma styles. 
For custom styles you have the part in the name `radii/sm` → `--radii-sm`

I hope that helps, otherwise let me know what is still unclear.

**Comment by mwargan** [comment]
Hey @lukasoppermann - thanks dearly for helping!

This is definitely coming down to my lack of experience with Style Dictionaries. I guess my confusion also comes to: the transform groups (especially for CSS) include some existing transformations: https://amzn.github.io/style-dictionary/#/transform_groups?id=css.

As an example, that transform group includes a transform for colours, namely converting to hex if the alpha channel is 100% opacity: https://amzn.github.io/style-dictionary/#/transforms?id=colorcss, but that doesn't seem to be happening in your transformer repo. I was thinking that it's not working due to a naming convention, but I'm way off, right :P?

**Comment by lukasoppermann** [comment]
Hey, this may be, because the name that is used is `sizes` and not `size`. 

Could you maybe try to adjust your json and rename `sizes` to `size` (manually) and see if this works?
This would give us an idea of how we may be able to fix it.

**Comment by mwargan** [comment]
Hey @lukasoppermann - on it. I've opened the relevant issue here: https://github.com/lukasoppermann/design-token-transformer/issues/4 feel free to close either and just let me know where you'd like to continue.

**Comment by mwargan** [comment]
@lukasoppermann after further review, seems I don't have "sizes". The nearest is maybe "fontSize" in the .json file.

**Comment by lukasoppermann** [comment]
Okay, this is something I will have to investigate.

Normally style dictionary converts using cti syntax, but the plugin may not adhere to this format which may create the issue.
Alternatively the issue could be that the category does not match.

Can you do me a favour and add `"category": "size"` in the json on the gutterSize and a fontSize?

```json
"gutterSize": {
  "category": "size",
  "value": 24,
  "type": "number",
  "unit": "pixel"
}
```

And afterwards try if the conversion works?

**Comment by mwargan** [comment]
@lukasoppermann just tried adding the category key-value pair to both gutterSize and fontSize - still no dice :/

**Comment by lukasoppermann** [comment]
Okay. Thank you for testing it. I will look into the issue and try to solve it.

**Comment by klarkc** [comment]
I am having this same issue, the figma plugin is exporting this:

```json
{
    "tiny": {
        "fontFamily": {
            "type": "string",
            "value": "Avenir LT Pro"
        },
        "fontSize": {
            "type": "number",
            "unit": "pixel",
            "value": 32
        },
        "lineHeight": {
            "type": "string",
            "unit": "auto",
            "value": "normal"
        },
        ...
    }
}
```

But it should be this:

```json
{
    "fontFamily": {
        "tiny": {
            "type": "string",
            "value": "Avenir LT Pro"
        }
    },
    "fontSize": {
        "tiny": {
            "type": "number",
            "unit": "pixel",
            "value": 32
        }
    },
    "lineHeight": {
        "tiny": {
            "type": "string",
            "unit": "auto",
            "value": "normal"
        }
    },
    ...
}
```

**Comment by lukasoppermann** [comment]
Hey @klarkc 
is this an issue just with tailwind or does this solve the issue for amazon style dictionary?

**Comment by klarkc** [comment]
@lukasoppermann both, the tool that I use to extract tailwind config from the exported dictionary [expects CTI standard](https://github.com/michaelmang/tempera/tree/master/packages/tailwind#tokens).

**Comment by klarkc** [comment]
An option to enable / disable CTI convention on plugin settings is a viable solution?

**Comment by lukasoppermann** [comment]
Hey @klarkc so you tested with the inverted syntax and that solves the problem? 

Adding an option to enable / disable CTI is definitely an option. Would you be interested in sending a PR?

**Comment by klarkc** [comment]
@lukasoppermann yes it solves.

About a PR, right now I can't, but I'll try to make it as soon as possible, cause it's a big blocker here.

**Comment by lukasoppermann** [comment]
Just FYI @klarkc I added custom transformer examples to the design tokens transformer repo: https://github.com/lukasoppermann/design-token-transformer/blob/main/transformTokens.js so you can copy and adapt this to get the desired result.

e.g. this one matches any token on the json file that has the `unit` set to `pixel` and adds `px` to the end of the value.

```
StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  matcher: token => {
    return token.unit === 'pixel' && token.value !== 0
  },
  transformer: token => {
    return `${token.value}px`
  },
})
```
