### ISSUE TITLE
Gradient exported with fill category

### ISSUE THREAD

**Issue by xseignard** [lukasoppermann/design-tokens#84]
Hi!
First of all, thanks for this great plugin!

It seems that at one point, gradients were exported with the category `gradient` but it was then reverted to `fill` category.
See https://github.com/lukasoppermann/design-tokens/commit/ea8503d6ba508374f7f2b4aca679087926192cbd

Is there a reason why ? And would it be possible to add back this feature ?

Thanks!

**Comment by lukasoppermann** [comment]
Good question, I am actually not aware of any real reason.

I would be open to it being added back. Would you be willing to send a PR for this?

**Comment by xseignard** [comment]
Sure! I'll try to find time to handle that this week. I keep you posted
